import MUIThemeProvider from '@/components/common/MUIThemeProvider'
import Header from '@/components/layout/Header'
import { headerHeight } from '@/styles'
import { Stack } from '@mui/material'
import type { Metadata } from 'next'
import './animations.css'
import './globals.css'

export const metadata: Metadata = {
	title: 'CSE6242-Team145',
	description: 'Generated by create next app',
}

import './globals.css'

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<MUIThemeProvider>
				<Stack
					component={'body'}
					sx={{
						width: 1,
						height: `calc(100vh - ${headerHeight}px)`,
						overflowY: 'overlay',
						pt: `${headerHeight}px`,
					}}
				>
					<Header />
					{children}
				</Stack>
			</MUIThemeProvider>
		</html>
	)
}
